In [1]:
import numpy as np

A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

C = np.dot(A, B)

print("行列の積 C:")
print(C)

print("Cの要素の最大値:", np.max(C))


行列の積 C:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
Cの要素の最大値: 47
